plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-relative-links
  - jekyll-autoprefixer
  - jekyll/figure

url: "http://localhost:8080"
baseurl: ""

sass:
  style: expanded

pagination:
  per_page: 5