plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-relative-links
  - jekyll-autoprefixer
  - jekyll-figure
  - jekyll-sitemap

url: ""
baseurl: ""

sass:
  style: expanded

pagination:
  per_page: 5