name: Build german site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/builder:latest \
        /bin/bash -c "chmod 777 /srv/jekyll && chmod 777 build && cd build && chmod +x jekyll-build.sh && ./jekyll-build.sh"
